version: '3'

services:
  ml-notebook:
    # path to Dockerfile, which is in current directory w/ docker-compose.yml
    build: .
    container_name: ml-notebook-container
    working_dir: /home/jovyan/work
    volumes: 
      - ${PWD}:/home/jovyan/work
    ports:
      - 8888:8888
      - 8000:8000

